"""followers

Revision ID: 945468e63557
Revises: ee84d47e45b4
Create Date: 2020-03-02 12:48:58.424774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945468e63557'
down_revision = 'ee84d47e45b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
